### ISSUE TITLE
Error in Prediction on unannotated data

### ISSUE THREAD

**Issue by fairy-of-9** [swabhs/open-sesame#45]
Hi! I want to prediction on unannotated data.
I made "sentences.txt" in root directory.
I made "logs" directory in root directroy and extract pre-trained models in it.

I run this command :
`python -m sesame.targetid --mode predict --model_name fn1.7-pretrained-targetid --raw_input sentences.txt`

result logs : 
```
DATA_DIRECTORY: data/
DEBUG_MODE:     False
EMBEDDINGS_FILE:        data/glove.6B.100d.txt
VERSION:        1.7
_____________________
COMMAND: /data/open-sesame/sesame/targetid.py --mode predict --model_name fn1.7-pretrained-targetid --raw_input sentences.txt
MODEL FOR TEST / PREDICTION:    logs/fn1.7-pretrained-targetid/best-targetid-1.7-model
PARSING MODE:   predict
_____________________


Reading data/neural/fn1.7/fn1.7.fulltext.train.syntaxnet.conll ...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/open-sesame/sesame/targetid.py", line 62, in <module>
    train_examples, _, _ = read_conll(train_conll)
  File "sesame/dataio.py", line 32, in read_conll
    with codecs.open(conll_file, "r", "utf-8") as cf:
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'data/neural/fn1.7/fn1.7.fulltext.train.syntaxnet.conll'
```

Did I miss anything?
Thanks!

**Comment by fairy-of-9** [comment]
I'm using python 2.7.12

**Comment by fairy-of-9** [comment]
This issue was solved by running the **Data Preprocessing** in readme.
