### ISSUE TITLE
Glove word embedding links returns 404

### ISSUE THREAD

**Issue by marquesarthur** [swabhs/open-sesame#62]
In the second step: 
```
Second, this project uses pretrained GloVe word embeddings of 100 dimensions, trained on 6B tokens. Download and extract under $DATA/embeddings_glove/.
```

The link to glove http://nlp.stanford.edu/data/glove.6B.100d.zip seems broken

**Comment by jayralencar** [comment]
I downloaded it from http://nlp.stanford.edu/data/glove.6B.zip, but the dimensions do not match.

```
Reading model from logs/fn1.7-pretrained-targetid/best-targetid-1.7-model ...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jayr/dev/open-sesame/sesame/targetid.py", line 459, in <module>
    model.populate(model_file_name)
  File "_dynet.pyx", line 1461, in _dynet.ParameterCollection.populate
  File "_dynet.pyx", line 1516, in _dynet.ParameterCollection.populate_from_textfile
RuntimeError: Dimensions of lookup parameter /_0 lookup up from file ({100,400574}) do not match parameters to be populated ({100,410050})
```

**Comment by ncaq** [comment]
A note for the explorer.
I thought it might be due to the lack of aligned dyNET versions, so I aligned them.
The old version of dyNET cannot be installed due to Eigen's change of host location, so I patched that only.
[ncaq/dynet at fix-v2.0.z-url](https://github.com/ncaq/dynet/tree/fix-v2.0.z-url)
Also, the type of the init attribute was different, so I decided to let init be the default.
And I got the same error.

~~~console
Loading model from logs/fn1.7-pretrained-frameid/best-frameid-1.7-model ...
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ncaq/Desktop/open-sesame/sesame/frameid.py", line 369, in <module>
    model.populate(model_file_name)
  File "_dynet.pyx", line 1061, in _dynet.ParameterCollection.populate
  File "_dynet.pyx", line 1116, in _dynet.ParameterCollection.populate_from_textfile
RuntimeError: Dimensions of lookup parameter /_0 lookup up from file ({100,400574}) do not match parameters to be populated ({100,410050})
~~~
